from enum import Enum, auto


class MessageType(Enum):
    SYSTEM = auto()
    ERROR = auto()
    AUTH_REQUEST = auto()
    AUTH_RESPONSE = auto()
    AUTH_SUCCESS = auto()
    AUTH_FAILURE = auto()
    AUTH_PAYLOAD = auto()
    AUTH_VALIDATE = auto()
    ROOM_DESCRIPTION = auto()
    ROOM_EXITS = auto()
    ROOM_PLAYERS = auto()
    PROMPT = auto()
    INPUT = auto()
    COMMAND = auto()
    SAY = auto()
    TELL = auto()
    EMOTE = auto()
    ROOM_MESSAGE = auto()
    COMBAT_START = auto()
    COMBAT_ACTION = auto()
    COMBAT_END = auto()
    HEALTH_UPDATE = auto()
    MANA_UPDATE = auto()
    MOVEMENT_UPDATE = auto()
    STATS_UPDATE = auto()
    INVENTORY = auto()
    ITEM_GET = auto()
    ITEM_DROP = auto()
    ITEM_USE = auto()

    WELCOME = auto()
    DISCONNECT = auto()
    ANSI_PROMPT = auto()
